#define PIPE_PIPE                        1
#define AMP_AMP                          2
#define PIPE                             3
#define SEMI                             4
#define NL                               5
#define COMMAND                          6
#define EVALUATE                         7
#define BREAK                            8
#define CONTINUE                         9
#define EXIT                            10
#define ERROR                           11
#define LPAREN                          12
#define RPAREN                          13
#define BEGIN                           14
#define END                             15
#define LOOP                            16
#define FOR                             17
#define IF                              18
#define ELSE_IF                         19
#define ELSE                            20
