name: CMake MacOS 11

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2

    - name: xcode 12.2
      shell: bash
      run: sudo xcode-select -s /Applications/Xcode_12.2.app

    - name: Brew
      run: brew install ragel

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: mpw fat
        path: ${{runner.workspace}}/build/mpw-shell
